name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.9.0
        env:
            CIBW_BUILD: 'cp36-* cp37-* cp38-* cp39-* cp310-*'
            CIBW_ARCHS_MACOS: "x86_64 arm64"
            CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7,<3.11"
        #   CIBW_SKIP: "*-win32 *-manylinux_i686"
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

